pipeline:
  build:
    image: golang:latest
    commands:
      - make
#      - rm -rf build/_workspace
#      - rm .drone.yml
#      - rm -rf .git

  stop:
    image: appleboy/drone-ssh
    host: etc.minerpool.co
    username: ubuntu
    key: ${SSH_KEY}
    secrets: [ SSH_KEY ]
    command_timeout: 600
    script:
      - sudo /bin/systemctl stop oepool oeapi oepayout oeunlock || true

  copy:
    image: appleboy/drone-scp
    host: etc.minerpool.co
    username: ubuntu
    key: ${SSH_KEY}
    secrets: [ SSH_KEY ]
    target: /tmp/oetest/
    source: build/bin/open-ethereum-pool

  start:
    image: appleboy/drone-ssh
    host: etc.minerpool.co
    username: ubuntu
    key: ${SSH_KEY}
    secrets: [ SSH_KEY ]
    command_timeout: 600
    script:
      - sudo /bin/systemctl start oepool oeapi oepayout oeunlock
